# Program 8(a):Deploy Support Vector Machine

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\HP\Downloads\diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [3]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [4]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [5]:
print('N0. of zero values in Glucose',df[df['Glucose']==0].shape[0])
print('N0. of zero values in BloodPressure',df[df['BloodPressure']==0].shape[0])
print('N0. of zero values in SkinThickness',df[df['SkinThickness']==0].shape[0])
print('N0. of zero values in Insulin',df[df['Insulin']==0].shape[0])
print('N0. of zero values in BMI',df[df['BMI']==0].shape[0])

N0. of zero values in Glucose 5
N0. of zero values in BloodPressure 35
N0. of zero values in SkinThickness 227
N0. of zero values in Insulin 374
N0. of zero values in BMI 11


In [6]:
df['Glucose']=df['Glucose'].replace(0,df['Glucose'].mean())
df['BloodPressure']=df['BloodPressure'].replace(0,df['BloodPressure'].mean())
df['SkinThickness']=df['SkinThickness'].replace(0,df['SkinThickness'].mean())
df['Insulin']=df['Insulin'].replace(0,df['Insulin'].mean())
df['BMI']=df['BMI'].replace(0,df['BMI'].mean())

In [7]:
print('N0. of zero values in Glucose',df[df['Glucose']==0].shape[0])
print('N0. of zero values in BloodPressure',df[df['BloodPressure']==0].shape[0])
print('N0. of zero values in SkinThickness',df[df['SkinThickness']==0].shape[0])
print('N0. of zero values in Insulin',df[df['Insulin']==0].shape[0])
print('N0. of zero values in BMI',df[df['BMI']==0].shape[0])

N0. of zero values in Glucose 0
N0. of zero values in BloodPressure 0
N0. of zero values in SkinThickness 0
N0. of zero values in Insulin 0
N0. of zero values in BMI 0


In [8]:
x=df[['Pregnancies','Insulin','SkinThickness','BMI','Age','Glucose','BloodPressure','DiabetesPedigreeFunction']]
y=df['Outcome']

In [9]:
x

Pregnancies     Insulin  SkinThickness   BMI  Age  Glucose  \
0              6   79.799479      35.000000  33.6   50    148.0   
1              1   79.799479      29.000000  26.6   31     85.0   
2              8   79.799479      20.536458  23.3   32    183.0   
3              1   94.000000      23.000000  28.1   21     89.0   
4              0  168.000000      35.000000  43.1   33    137.0   
..           ...         ...            ...   ...  ...      ...   
763           10  180.000000      48.000000  32.9   63    101.0   
764            2   79.799479      27.000000  36.8   27    122.0   
765            5  112.000000      23.000000  26.2   30    121.0   
766            1   79.799479      20.536458  30.1   47    126.0   
767            1   79.799479      31.000000  30.4   23     93.0   

     BloodPressure  DiabetesPedigreeFunction  
0             72.0                     0.627  
1             66.0                     0.351  
2             64.0                     0.672  
3             66.0                     0.167  
4             40.0                     2.288  
..             ...                       ...  
763           76.0                     0.171  
764           70.0                     0.340  
765           72.0                     0.245  
766           60.0                     0.349  
767           70.0                     0.315  

[768 rows x 8 columns]

In [10]:
y.values

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [11]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x)
X=scaler.transform(x)

In [12]:
# Splitting Dataset into Training and Test Set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)


## Linear kernel

In [13]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='linear')
svclassifier.fit(x_train,y_train)

SVC(kernel='linear')

In [14]:
y_pred=svclassifier.predict(x_test)

In [15]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[88 11]
 [24 31]]
              precision    recall  f1-score   support

           0       0.79      0.89      0.83        99
           1       0.74      0.56      0.64        55

    accuracy                           0.77       154
   macro avg       0.76      0.73      0.74       154
weighted avg       0.77      0.77      0.76       154



## poly kernel

In [16]:
from sklearn import metrics
svclassifier=SVC(kernel='poly',degree=6)
svclassifier.fit(x_train,y_train)

SVC(degree=6, kernel='poly')

In [17]:
y_pred=svclassifier.predict(x_test)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[98  1]
 [30 25]]
              precision    recall  f1-score   support

           0       0.77      0.99      0.86        99
           1       0.96      0.45      0.62        55

    accuracy                           0.80       154
   macro avg       0.86      0.72      0.74       154
weighted avg       0.84      0.80      0.78       154



## Gaussian kernel

In [19]:
from sklearn.svm import SVC
svclassifier=SVC(kernel="rbf",degree=3)
svclassifier.fit(x_train,y_train)

SVC()

In [20]:
y_pred=svclassifier.predict(x_test)

In [21]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[94  5]
 [27 28]]
              precision    recall  f1-score   support

           0       0.78      0.95      0.85        99
           1       0.85      0.51      0.64        55

    accuracy                           0.79       154
   macro avg       0.81      0.73      0.75       154
weighted avg       0.80      0.79      0.78       154



## Sigmoid kernel

In [22]:
from sklearn.svm import SVC
svclassifier=SVC(kernel="sigmoid",degree=0)
svclassifier.fit(x_train,y_train)

SVC(degree=0, kernel='sigmoid')

In [23]:
y_pred=svclassifier.predict(x_test)

In [24]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[77 22]
 [22 33]]
              precision    recall  f1-score   support

           0       0.78      0.78      0.78        99
           1       0.60      0.60      0.60        55

    accuracy                           0.71       154
   macro avg       0.69      0.69      0.69       154
weighted avg       0.71      0.71      0.71       154

